### ISSUE TITLE
KShift is somehow convinced that my location has a sunset at 7:42 in the morning and the sunrise at 9:38 at night.

### ISSUE THREAD

**Issue by daemonspudguy** [justjokiing/kshift#10]
My location code is USOH556, for reference.

**Comment by justjokiing** [comment]
That does not seem to be a valid location code. A valid code should give you correct sunset/sunrise times.

**Comment by daemonspudguy** [comment]
I mistyped. I meant USOH0556

**Comment by justjokiing** [comment]
Have you been using KShift prior to this issue? It may be that the way I parse the sunrise/sunset times has been affected by the information provider.

**Comment by daemonspudguy** [comment]
No. I only switched to KDE last week.

**Comment by justjokiing** [comment]
I will take a look at my parsing function later next week and hopefully have a fix for you. 

For now, I recommend adding the line below to turn off sunrise/sunset fetching. 
`webdata: false`

Then set your sunrise/sunset times to whatever suits.

**Comment by prey169** [comment]
This just happened to me as well over the last couple days. Different location code as well

**Comment by prey169** [comment]
Found the bug. The times list in conf.py is pulling in (town), (State) of TIME am/pm zone within https://weather.com/weather/today/l/code as the first time, sunset was pushed to the second item in the array, with sunset being last now.

Ill push a commit. Feel Free to approve/decline or whatever.  (though not sure what the etiquette for your repo is on this but this fix worked for me)

**Comment by justjokiing** [comment]
Thank you for this fix!
