### ISSUE TITLE
Is there support for wallpaper slideshow?

### ISSUE THREAD

**Issue by notalexnot** [justjokiing/kshift#11]
Hey!

I want to try KShift since I've always wanted auto dark/light mode, but do i have to set a wallpaper path or can I leave it blank? In case I can't, is there support for slideshow or do I need to add the path of every wallpaper? Btw, I use two monitors, would setting a wallpaper affect both? Sorry if this isn't the place or if I did miss some information, didn't know where else to ask :/

Thanks in advance, this is a very cool and native approach to this need!

**Comment by justjokiing** [comment]
You can just comment out or remove the wallpaper variable for the specific theme and Kshift will not do any wallpaper actions. 

This does not have any direct support for a wallpaper slideshow, but could be done manually if you set the `time` variable for each wallpaper theme in the intervals you wanted. For example, you could have:

```
wallpaper1:
    time: '*:00:00'
wallpaper2:
    time: '*:30:00'
```
This, coupled with the wallpaper variable of your choice, would alternate between wallpaper1 and wallpaper2 every 30 minutes. This is a bit tedious, but would achieve some sort of wallpaper slide show.

Setting the wallpaper is done by `plasma-apply-wallpaper`, which seems to set all desktop backgrounds to the wallpaper chosen.

This is definitely the right place to ask, thanks for using Kshift.

**Comment by notalexnot** [comment]
Thanks, I'll be using it! I guess it's solved now :)
