### ISSUE TITLE
SyntaxError in line 58 of utils.py

### ISSUE THREAD

**Issue by notalexnot** [justjokiing/kshift#14]
Hey!

I was trying to install kshift again, but I couldn't because of the following error in the `utils.py` script:

https://github.com/justjokiing/kshift/blob/e772af8a9cd4f679c186edb2f7d3eab3548e93dd/src/utils.py#L58

It was solved by changing the double quotes to single quotes, like this:

```python
kdeconfig_path = f"{os.path.expanduser('~')}/.config/kdeglobals"
```

**Comment by justjokiing** [comment]
Added this change to the most recent commit. Thank you for submitting the issue.
