### ISSUE TITLE
Correct time data is not saved

### ISSUE THREAD

**Issue by anders0nmat** [justjokiing/kshift#2]
After debugging, i noticed that no matter what is received from weather.com, the same (default) string is always saved to `kshift.timer`.
I noticed, that the string that is written to this file is static, the variables in there (`$sunrise` and `$sunset`) are only evaluated once, upon execution.
I fixed it by making the string a stringified `echo` command (`kshift_timer='echo -e "more stuff here"'`) and replacing the actual save command with `eval "$kshift_timer" > ...`. But i think this is not the best way to handle the issue.

**Comment by justjokiing** [comment]
The issue seems to be because I set up to update the timer at an odd time. I am working on restructuring how and when the update happens and will commit a fix soon. thank you for testing out kshift

**Comment by justjokiing** [comment]
Just committed an update, it comes with a remove function. Try to remove your current install and reinstall. Let me know if your problem persists and we can work to fix it
