### ISSUE TITLE
Cannot execute: required file not found

### ISSUE THREAD

**Issue by cameronj86** [justjokiing/kshift#5]
**Expected behavior**: Install proceeds
**Current behavior**: Install stops @ step 3 

Code:
**cameronj86** ./kshift --install
**bash**: ./kshift: cannot execute: required file not found

**Comment by cameronj86** [comment]
I checked and I have python3, systemd and I am currently running KDE

**Comment by justjokiing** [comment]
Can you screen shot your terminal?

If you cannot execute the command `kshift` after install, then you may not have `~./local/bin/` in your path.
